modLoader="javafml"
loaderVersion="${loader_version_range}"
license="$MIT"

[[mods]]
modId="mlrm"
version="1.0"
displayName="Mekanism: Liquid Radioactive Material"
authors="FixedDolphin927"

description='''A mod that allows Mekanism radioactive material to be turned into liquid
'''
[[dependencies.mlrm]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.mlrm]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"