modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mlrm"
version="1.0"
displayName="Mekanism: Liquid Radioactive Material"
authors="FixedDolphin927"

description='''${mod_description}'''
[[dependencies.mlrm]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.mlrm]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"